---
# Common mailrise Docker setup for Discord notifications
- name: Check if Docker is installed and running
  command: docker info
  register: docker_check
  failed_when: false
  changed_when: false
  when: mail_config.enable_mailrise | default(true)
  tags: [mail, security, install]

- name: Notify if Docker is not available
  debug:
    msg: "Docker is not installed or not running. Mailrise will be skipped. Install Docker to use mailrise for Discord notifications."
  when: mail_config.enable_mailrise | default(true) and docker_check.rc != 0
  tags: [mail, security, install]

- name: Create mailrise directory
  file:
    path: /opt/mailrise
    state: directory
    mode: '0755'
    owner: root
    group: root
  when: mail_config.enable_mailrise | default(true) and docker_check.rc == 0
  tags: [mail, security, install]

- name: Deploy mailrise docker-compose.yml
  copy:
    content: |
      services:
        mailrise:
          container_name: mailrise
          image: yoryan/mailrise
          volumes:
            - ./mailrise.conf:/etc/mailrise.conf:ro
          ports:
            - "8025:8025"
          restart: unless-stopped
    dest: /opt/mailrise/docker-compose.yml
    mode: '0644'
    owner: root
    group: root
  when: mail_config.enable_mailrise | default(true) and docker_check.rc == 0
  notify: restart mailrise
  tags: [mail, security, config]

- name: Create mailrise user
  user:
    name: mailrise
    system: yes
    shell: /bin/false
    home: /nonexistent
    create_home: no
  when: mail_config.enable_mailrise | default(true) and docker_check.rc == 0
  tags: [mail, security, install]

- name: Configure mailrise
  template:
    src: mailrise.conf.j2
    dest: /opt/mailrise/mailrise.conf
    backup: yes
    mode: '0644'
    owner: root
    group: root
  when: mail_config.enable_mailrise | default(true) and docker_check.rc == 0
  notify: restart mailrise
  tags: [mail, security, config]

- name: Start mailrise container
  command: docker compose up -d
  args:
    chdir: /opt/mailrise
  when: mail_config.enable_mailrise | default(true) and docker_check.rc == 0
  tags: [mail, security, config]