---
# Distribution-specific mail configuration
- name: Include distribution-specific mail tasks
  include_tasks: "{{ ansible_os_family }}.yml"

# Common mailrise Docker setup (when enabled)
- name: Include mailrise setup tasks
  include_tasks: mailrise-common.yml