---
- name: Install common and distribution-specific packages (Debian)
  apt:
    name: "{{ common_packages + core_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags: [packages, install]

- name: Install common and distribution-specific packages (Arch)
  pacman:
    name: "{{ common_packages + core_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Archlinux"
  tags: [packages, install]

