---
# Update package cache before installation
- name: Update package cache
  package:
    update_cache: yes
  tags: [packages, install]

- name: Install common and distribution-specific packages
  package:
    name: "{{ common_packages + core_packages }}"
    state: present
  tags: [packages, install]