---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: [upgrades, security]

- name: Install unattended-upgrades package
  apt:
    name: unattended-upgrades
    state: present
  tags: [upgrades, security, install]

- name: Configure unattended-upgrades
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    backup: yes
  tags: [upgrades, security, config]

- name: Configure auto upgrades
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    backup: yes
  tags: [upgrades, security, config]

