---
# Common user creation and shell setup
- name: Ensure deploy user exists
  user:
    name: "{{ deploy_user }}"
    shell: /bin/bash
    state: present
    create_home: yes
  when: deploy_user != "root"
  tags: [user-management, deploy-user, config]

- name: Ensure actual user exists
  user:
    name: "{{ server_user }}"
    shell: "{{ user_shell }}"
    state: present
    create_home: yes
  when: server_user != "root"
  tags: [user-management, user, config]

- name: Add actual user to groups
  user:
    name: "{{ server_user }}"
    groups: "{{ user_groups }}"
    append: yes
  when: server_user != "root"
  tags: [user-management, user, config]

- name: Install fisher for fish shell
  shell: |
    sudo -u "{{ server_user }}" -H bash -c 'curl -sL https://git.io/fisher | fish -c "source; and fisher install jorgebucaran/fisher"'
  args:
    creates: "/home/{{ server_user }}/.config/fish/functions/fisher.fish"
  when: user_shell == "/usr/bin/fish" and server_user != "root"
  tags: [user-management, user, install]