---
- name: Ensure user exists
  user:
    name: "{{ server_user }}"
    shell: "{{ user_shell }}"
    state: present
  when: server_user != "root"
  tags: [user-management, user, config]

- name: Add user to groups
  user:
    name: "{{ server_user }}"
    groups: "{{ user_groups }}"
    append: yes
  when: server_user != "root"
  tags: [user-management, user, config]

- name: Change shell for existing user
  user:
    name: "{{ server_user }}"
    shell: "{{ user_shell }}"
  when: server_user != "root"
  tags: [user-management, user, config]

- name: Install fisher for fish shell
  become_user: "{{ server_user }}"
  shell: |
    curl -sL https://git.io/fisher | fish -c 'source; and fisher install jorgebucaran/fisher'
  args:
    creates: ~/.config/fish/functions/fisher.fish
  when: user_shell == "/usr/bin/fish"
  tags: [user-management, user, install]