---
# Common user creation and shell setup
- name: Include common user management tasks
  include_tasks: common-users.yml

# Distribution-specific group management for deploy user
- name: Include distribution-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"