---
# Debian-specific configuration variables
# Common variables are defined in group_vars/all/config.yml

# Distribution-specific system configuration
package_manager: "apt"
motd_path: "/etc/update-motd.d"

# Debian-specific packages (extends common_packages from all/config.yml)
core_packages:
  - unattended-upgrades
  - ssmtp
  - fd-find

# User Configuration - Debian uses sudo group
user_groups:
  - sudo

# Unattended Upgrades Configuration (Debian-specific)
unattended_upgrades:
  # Inherits automatic_reboot settings from all/config.yml auto_reboot_config
  enable_auto_upgrades: true
  auto_upgrade_time: "01:30"
