---
- name: "Set hostname"
  hostname:
    name: "{{ hostname }}"
  when: hostname != ansible_hostname
  tags: [system-basics, system, config]

- name: Add hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ hostname }}"
    backup: yes
  tags: [system-basics, system, config]

- name: Generate locales
  locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ locales }}"
  tags: [system-basics, system, config]

- name: Set timezone
  timezone:
    name: "{{ timezone }}"
  tags: [system-basics, system, config]


# Distribution-specific system basics tasks
- name: Include distribution-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"