---
- name: "Set hostname to {{ hostname }}"
  hostname:
    name: "{{ hostname }}"
  when: hostname != ansible_hostname

- name: Add hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ hostname }}"
    backup: yes

- name: Generate locales
  locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ locales }}"

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Configure timezone file
  copy:
    content: "{{ timezone }}\n"
    dest: /etc/timezone
    backup: yes
  notify: reconfigure tzdata

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600