---
- name: "Set hostname"
  hostname:
    name: "{{ hostname }}"
  when: hostname != ansible_hostname
  tags: [system-basics, system, config]

- name: Add hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ hostname }}"
    backup: yes
  tags: [system-basics, system, config]

- name: Generate locales
  locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ locales }}"
  tags: [system-basics, system, config]

- name: Set timezone
  timezone:
    name: "{{ timezone }}"
  tags: [system-basics, system, config]

- name: Install QEMU guest agent on virtual machines
  package:
    name: qemu-guest-agent
    state: present
  when: ansible_virtualization_type in ['qemu', 'kvm']
  tags: [system-basics, system, virtualization]

- name: Update package cache
  package:
    update_cache: yes
    cache_valid_time: "{{ 3600 if ansible_os_family == 'Debian' else omit }}"
  tags: [system-basics, system]

- name: Create custom mount directories
  file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
  loop: "{{ vault_fstab_mounts | default([]) }}"
  when: vault_fstab_mounts is defined
  tags: [system-basics, fstab, storage]

- name: Configure custom fstab entries
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    dump: "{{ item.dump | default('0') }}"
    passno: "{{ item.passno | default('0') }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ vault_fstab_mounts | default([]) }}"
  when: vault_fstab_mounts is defined
  tags: [system-basics, fstab, storage]