---
# Arch Linux MOTD configuration using /etc/profile.d/motd.sh
- name: Create dynamic MOTD script for Arch Linux
  template:
    src: motd.sh.j2
    dest: /etc/profile.d/motd.sh
    mode: "0755"
    owner: root
    group: root
  tags: [motd, config]