---
- name: Remove default /etc/motd file
  file:
    path: /etc/motd
    state: absent
    backup: yes

- name: Deploy MOTD welcome script (replaces generic header)
  template:
    src: 05-welcome.j2
    dest: /etc/update-motd.d/05-welcome
    mode: '0755'
    owner: root
    group: root
  when: motd_config.enable_welcome | default(true)

- name: Deploy MOTD system info script (complements existing uname)
  template:
    src: 11-sysinfo.j2
    dest: /etc/update-motd.d/11-sysinfo
    mode: '0755'
    owner: root
    group: root
  when: motd_config.enable_sysinfo | default(true)

- name: Deploy MOTD security updates script
  template:
    src: 30-security-updates.j2
    dest: /etc/update-motd.d/30-security-updates
    mode: '0755'
    owner: root
    group: root
  when: motd_config.enable_security_updates | default(true)

- name: Deploy MOTD footer script
  template:
    src: 95-footer.j2
    dest: /etc/update-motd.d/95-footer
    mode: '0755'
    owner: root
    group: root
  when: motd_config.enable_footer | default(true)

- name: Update MOTD
  command: update-motd
  changed_when: false