---
# Common setup: Remove default /etc/motd file
- name: Remove default /etc/motd file
  file:
    path: /etc/motd
    state: absent
  tags: [motd, config]

# Distribution-specific MOTD configuration
- name: Include distribution-specific MOTD tasks
  include_tasks: "{{ ansible_os_family }}.yml"

