---
- name: Install Docker and configure user access
  hosts: debian_servers
  become: true

  roles:
    - docker

  post_tasks:
    - name: Display Docker setup completion message
      debug:
        msg:
          - "Docker setup completed successfully!"
          - ""
          - "Next steps:"
          - "1. Log out and log back in for group changes to take effect"
          - "2. Test Docker access: docker run hello-world"
          - "3. Consider setting up Docker Compose for multi-container applications"

    - name: Remind about group membership
      debug:
        msg: "User '{{ server_user }}' has been added to the docker group. A logout/login is required for group changes to take effect."
      when: server_user != "root"