---
- name: Complete Debian server setup
  hosts: debian_servers
  become: true

  roles:
    - system-basics
    - packages
    - motd-config
    - user-management
    - mail-config
    - unattended-upgrades

  post_tasks:
    - name: Display setup completion message
      debug:
        msg:
          - "Server setup completed successfully!"
          - ""
          - "Next steps:"
          - "1. Apply Chezmoi setup for user-level configurations"
          - "2. Verify mail configuration is working"  
          - "3. Test unattended upgrades functionality"
